// Strong-symbol override copy of recompiled YieldAndCheckThreshold_82CBD098 (generated file: fable_2_recomp.223.cpp).
// Generated by tools/make_hotfunc_overrides.py - do not edit by hand.
// Active transforms: nv=1 mfmsr=0 glock=0 gt=0
//
// The recompiler emits recompiled guest functions as WEAK extern "C" aliases
// of __imp__YieldAndCheckThreshold_82CBD098; fable_2_register.cpp registers the ALIAS in the
// indirect-dispatch table. This strong definition intercepts both direct bl
// calls and bctrl dispatch. __imp__YieldAndCheckThreshold_82CBD098 remains the original.
#include "fable_2_pch.h"

// Non-volatile equivalents of the pch's REX_LOAD_*/REX_STORE_* macros
// (identical address math, bswap, and byte order; no volatile).
#define GV8(x)   (*(const uint8_t*)(REX_RAW_ADDR(x)))
#define GV16(x)  __builtin_bswap16(*(const uint16_t*)(REX_RAW_ADDR(x)))
#define GV32(x)  __builtin_bswap32(*(const uint32_t*)(REX_RAW_ADDR(x)))
#define GV64(x)  __builtin_bswap64(*(const uint64_t*)(REX_RAW_ADDR(x)))
#define SV8(x, y)   (*(uint8_t*)(REX_RAW_ADDR(x)) = (y))
#define SV16(x, y)  (*(uint16_t*)(REX_RAW_ADDR(x)) = __builtin_bswap16(y))
#define SV32(x, y)  (*(uint32_t*)(REX_RAW_ADDR(x)) = __builtin_bswap32(y))
#define SV64(x, y)  (*(uint64_t*)(REX_RAW_ADDR(x)) = __builtin_bswap64(y))

// Batched NtYieldExecution (see header).
#include "hotfunc/hotfunc_yield.h"
extern "C" void YieldAndCheckThreshold_82CBD098(PPCContext& __restrict ctx, uint8_t* base) {
	REX_FUNC_PROLOGUE();
	uint32_t ea{};
	// mflr r12
	ctx.r12.u64 = ctx.lr;
	// stw r12,-8(r1)
	SV32(ctx.r1.u32 + -8, ctx.r12.u32);
	// stwu r1,-96(r1)
	ea = -96 + ctx.r1.u32;
	SV32(ea, ctx.r1.u32);
	ctx.r1.u32 = ea;
	// bl 0x832b28ec
	ctx.lr = 0x82CBD0A8;
	// NtYieldExecution = MaybeYield() (SwitchToThread + barrier) and always
	// returns X_STATUS_SUCCESS; the threshold math below is a constant as a
	// result. Batch the real yield (config: [perf] hotfunc_yield_every).
	fable2::hotfunc::BatchedYield();
	ctx.r3.s64 = 0; // X_STATUS_SUCCESS
	// lis r11,16384
	ctx.r11.s64 = 1073741824;
	// ori r11,r11,36
	ctx.r11.u64 = ctx.r11.u64 | 36;
	// subf r11,r3,r11
	ctx.r11.u64 = ctx.r11.u64 - ctx.r3.u64;
	// cntlzw r11,r11
	ctx.r11.u64 = ctx.r11.u32 == 0 ? 32 : __builtin_clz(ctx.r11.u32);
	// rlwinm r11,r11,27,31,31
	ctx.r11.u64 = __builtin_rotateleft64(ctx.r11.u32 | (ctx.r11.u64 << 32), 27) & 0x1;
	// xori r3,r11,1
	ctx.r3.u64 = ctx.r11.u64 ^ 1;
	// addi r1,r1,96
	ctx.r1.s64 = ctx.r1.s64 + 96;
	// lwz r12,-8(r1)
	ctx.r12.u64 = GV32(ctx.r1.u32 + -8);
	// mtlr r12
	ctx.lr = ctx.r12.u64;
	// blr 
	return;
}
