// Strong-symbol override copy of recompiled ResolveSubsystemReference_821F8760 (generated file: fable_2_recomp.130.cpp).
// Generated by tools/make_hotfunc_overrides.py - do not edit by hand.
// Active transforms: nv=1 mfmsr=1 glock=0 gt=0
//
// The recompiler emits recompiled guest functions as WEAK extern "C" aliases
// of __imp__ResolveSubsystemReference_821F8760; fable_2_register.cpp registers the ALIAS in the
// indirect-dispatch table. This strong definition intercepts both direct bl
// calls and bctrl dispatch. __imp__ResolveSubsystemReference_821F8760 remains the original.
#include "fable_2_pch.h"

extern "C" void ProcessAndProcessAndProcess1124_822641F0(PPCContext& ctx, uint8_t* base);

// Non-volatile equivalents of the pch's REX_LOAD_*/REX_STORE_* macros
// (identical address math, bswap, and byte order; no volatile).
#define GV8(x)   (*(const uint8_t*)(REX_RAW_ADDR(x)))
#define GV16(x)  __builtin_bswap16(*(const uint16_t*)(REX_RAW_ADDR(x)))
#define GV32(x)  __builtin_bswap32(*(const uint32_t*)(REX_RAW_ADDR(x)))
#define GV64(x)  __builtin_bswap64(*(const uint64_t*)(REX_RAW_ADDR(x)))
#define SV8(x, y)   (*(uint8_t*)(REX_RAW_ADDR(x)) = (y))
#define SV16(x, y)  (*(uint16_t*)(REX_RAW_ADDR(x)) = __builtin_bswap16(y))
#define SV32(x, y)  (*(uint32_t*)(REX_RAW_ADDR(x)) = __builtin_bswap32(y))
#define SV64(x, y)  (*(uint64_t*)(REX_RAW_ADDR(x)) = __builtin_bswap64(y))
extern "C" void ResolveSubsystemReference_821F8760(PPCContext& __restrict ctx, uint8_t* base) {
	REX_FUNC_PROLOGUE();
	uint32_t ea{};
	// mflr r12
	ctx.r12.u64 = ctx.lr;
	// stw r12,-8(r1)
	SV32(ctx.r1.u32 + -8, ctx.r12.u32);
	// stwu r1,-96(r1)
	ea = -96 + ctx.r1.u32;
	SV32(ea, ctx.r1.u32);
	ctx.r1.u32 = ea;
	// lis r11,-31927
	ctx.r11.s64 = -2092367872;
	// mr r5,r3
	ctx.r5.u64 = ctx.r3.u64;
	// lwz r11,26912(r11)
	ctx.r11.u64 = GV32(ctx.r11.u32 + 26912);
	// lwz r10,12(r11)
	ctx.r10.u64 = GV32(ctx.r11.u32 + 12);
	// lwz r11,140(r10)
	ctx.r11.u64 = GV32(ctx.r10.u32 + 140);
	// lbz r9,52(r11)
	ctx.r9.u64 = GV8(ctx.r11.u32 + 52);
	// cmplwi cr6,r9,0
	ctx.cr6.compare<uint32_t>(ctx.r9.u32, 0, ctx.xer);
	// beq cr6,0x821f87e0
	if (ctx.cr6.eq) goto loc_821F87E0;
	// clrlwi r10,r9,24
	ctx.r10.u64 = ctx.r9.u32 & 0xFF;
	// cmplwi cr6,r10,0
	ctx.cr6.compare<uint32_t>(ctx.r10.u32, 0, ctx.xer);
	// beq cr6,0x821f87a8
	if (ctx.cr6.eq) goto loc_821F87A8;
	// lbz r11,54(r11)
	ctx.r11.u64 = GV8(ctx.r11.u32 + 54);
	// cmplwi cr6,r11,0
	ctx.cr6.compare<uint32_t>(ctx.r11.u32, 0, ctx.xer);
	// li r11,1
	ctx.r11.s64 = 1;
	// bne cr6,0x821f87ac
	if (!ctx.cr6.eq) goto loc_821F87AC;
loc_821F87A8:
	// li r11,0
	ctx.r11.s64 = 0;
loc_821F87AC:
	// clrlwi r11,r11,24
	ctx.r11.u64 = ctx.r11.u32 & 0xFF;
	// cmplwi cr6,r11,0
	ctx.cr6.compare<uint32_t>(ctx.r11.u32, 0, ctx.xer);
	// beq cr6,0x821f87e0
	if (ctx.cr6.eq) goto loc_821F87E0;
	// li r4,2
	ctx.r4.s64 = 2;
	// mr r3,r5
	ctx.r3.u64 = ctx.r5.u64;
	// bl 0x822641f0
	ctx.lr = 0x821F87C4;
	ProcessAndProcessAndProcess1124_822641F0(ctx, base);
	// cmplwi cr6,r3,0
	ctx.cr6.compare<uint32_t>(ctx.r3.u32, 0, ctx.xer);
	// beq cr6,0x821f87e0
	if (ctx.cr6.eq) goto loc_821F87E0;
loc_821F87CC:
	// lwz r3,4(r3)
	ctx.r3.u64 = GV32(ctx.r3.u32 + 4);
	// addi r1,r1,96
	ctx.r1.s64 = ctx.r1.s64 + 96;
	// lwz r12,-8(r1)
	ctx.r12.u64 = GV32(ctx.r1.u32 + -8);
	// mtlr r12
	ctx.lr = ctx.r12.u64;
	// blr 
	return;
loc_821F87E0:
	// li r4,1
	ctx.r4.s64 = 1;
	// mr r3,r5
	ctx.r3.u64 = ctx.r5.u64;
	// bl 0x822641f0
	ctx.lr = 0x821F87EC;
	ProcessAndProcessAndProcess1124_822641F0(ctx, base);
	// cmplwi cr6,r3,0
	ctx.cr6.compare<uint32_t>(ctx.r3.u32, 0, ctx.xer);
	// bne cr6,0x821f87cc
	if (!ctx.cr6.eq) goto loc_821F87CC;
	// addi r1,r1,96
	ctx.r1.s64 = ctx.r1.s64 + 96;
	// lwz r12,-8(r1)
	ctx.r12.u64 = GV32(ctx.r1.u32 + -8);
	// mtlr r12
	ctx.lr = ctx.r12.u64;
	// blr 
	return;
}
